# MySQL.  Versions 4.1 and 5.0 are recommended.

development:
  adapter: mysql
  database: aardvark
  username: aardvark
  password: r00t
  pool: 5
  timeout: 5000

#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: aardvark_test
#  pool: 5
#  username: root
#  password:
#  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  database: aardvark
  username: aardvark
  password: r00t
  pool: 5
  timeout: 5000